<!doctype html>
<html lang="en">

<head>
  <title>English for welders</title>
  <?php include('../../../fragments/links-style-main.php') ?>

  <link href="../../../css/blog.css" rel="stylesheet">
  <link href="../../../css/style-main.css" rel="stylesheet">
  <link href="../../../css/sidebars.css" rel="stylesheet">
  <link href="../../../assets/dist/css/bootstrap.min.css" rel="stylesheet">

  <script src="../../../sidebars.js"></script>
  <script src="../../../assets/dist/js/bootstrap.bundle.min.js"></script> <!-- top menu -->

  <style>
    tr {
      border: solid 1px black;
    }

    td {
      border: solid 1px black;
      padding: 0.5rem;
    }

    .content {
      margin-bottom: 1rem;
    }
  </style>

</head>

<body>

  <div class="container">
    <?php include('../../../fragments/header.php'); ?>
  </div>

  <main class="container container2">
    <section class="home-section ">
      <div class="row">

        <div class="col-md-3">
          <?php includeWithVariables(
            '../../../fragments/nav-sidebar.php',
            array(
              'categoryLink1' => '../basic-information',
              'categoryLink2' => '../video',
              'categoryLink3' => '../vocabulary'
            ),
            array(
              'Symbols in Welding' => '../../topic1',
              'Alternative Types of Welding' => '../../topic2',
              'Arc and Gas Welding' => '../../topic3'
            )
          ); ?>
        </div> <!-- col-md-3 -->

        <div class="col-md-9">
          <div class="content">

            <div class="py-1 text-center container ">
              <h2 class="fw-light">Vocabulary - Alternative Types of Welding</h2>
            </div>

            <p>
              <strong>1.</strong> Learn the new words and phrases.
            </p>
            <p>
              cold welding ─ холодная сварка (в вакууме)
            </p>
            <p>
              lapped joints ─ соединение внахлестку
            </p>
            <p>
              diffusion bonding ─ диффузное соединение
            </p>
            <p>
              ultrasonic welding ─ ультразвуковая сварка
            </p>
            <p>
              explosive welding ─ сварка взрывом
            </p>
            <p>
              butt ─ стык
            </p>
            <p>
              anvil ─ наковальня
            </p>
            <p>
              honeycomb ─ пористый
            </p>
            <p>
              fin ─ ребро, пластина
            </p>
            <p>
              finished ─ готовый, обработанный
            </p>
            <p>
              integrated circuitry ─ интегральная схемотехника
            </p>
            <p>
              pneumatic tooling ─ пневматический инструмент
            </p>
            <p>
              punch presses ─ пресс-штамп
            </p>
            <p>
              <strong></strong>
            </p>
            <p>
              <strong>2.</strong> Match welding types (1-6) with their description (A-F). Then read the
              text and check your answers.
            </p>
            <table border="1" cellspacing="0" cellpadding="0">
              <tbody>
                <tr>
                  <td>
                    <p>
                      1. Cold welding
                    </p>
                  </td>
                  <td>
                    <p>
                      A. Light energy is used to weld parts together
                    </p>
                  </td>
                </tr>
                <tr>
                  <td>
                    <p>
                      2. Friction welding
                    </p>
                  </td>
                  <td>
                    <p>
                      B. The weld is formed at the expense of the applied
                      pressure at a high temperature for a long period of time
                    </p>
                  </td>
                </tr>
                <tr>
                  <td>
                    <p>
                      3. Laser welding
                    </p>
                  </td>
                  <td>
                    <p>
                      C. Vibration is used to generate heat necessary to produce
                      a weld.
                    </p>
                  </td>
                </tr>
                <tr>
                  <td>
                    <p>
                      4. Diffusion bonding
                    </p>
                  </td>
                  <td>
                    <p>
                      D. The heat to accomplish the joint is generated by
                      rotation
                    </p>
                  </td>
                </tr>
                <tr>
                  <td>
                    <p>
                      5. Ultrasonic welding
                    </p>
                  </td>
                  <td>
                    <p>
                      E. The most important factor to accomplish the weld is
                      pres-sure. No heat is applied.
                    </p>
                  </td>
                </tr>
                <tr>
                  <td>
                    <p>
                      6. Explosive welding
                    </p>
                  </td>
                  <td>
                    <p>
                      F. Rapid plastic deformation of the welded materials is
                      caused by detonation.
                    </p>
                  </td>
                </tr>
              </tbody>
            </table>
            <p>
              <strong>3.</strong> Fill in the blanks with the right words (namely, types of welding).
            </p>
            <p>
              1. …………………….welding is successfully used in manufacture of small elements
              of electric circuits.
            </p>
            <p>
              2. Heat is not used in …………….. welding.
            </p>
            <p>
              3. ………………….is widely used in aerospace industries.
            </p>
            <p>
              4. Vibration is used in ……………….welding.
            </p>
            <p>
              5. Plastic deformation is the basic principle in ……………welding.
            </p>
            <p>
              6. ……………. welding is impossible without pressure and high temperature.
            </p>
            <p>
              7. In …………..welding one of the parts being welded revolves.
            </p>
            <p>
              <strong>4.</strong> Translate the following sentences into Russian.
            </p>
            <p>
              1.При холодной сварке поверхности должны быть тщательноподготовлены.
            </p>
            <p>
              2. Скорость и толщина свариваемых деталей зависит не столько отмощности
              лазера, сколько от теплопроводности металла.
            </p>
            <p>
              3. Этот вид сварки наиболее широко используется в
              авиакосмическойпромышленности.
            </p>
            <p>
              4. Холодная сварка ─ это сварка без использования тепловой энергии, когда
              две свариваемые поверхности, обладающие высокойпластичностью, с силой
              прижимают друг к другу.
            </p>
            <p>
              5. Использование точечной и шовной сварки позволяет получатьсварные
              соединения высокой прочности.
            </p>
            <p>
              6. Основными переменными величинами при этом виде сварки являетсяподводимое
              тепло, время сварки и сила сжатия.
            </p>
            <p>
              7. Фрикционным разогревом добиваются пластичности материала, затем вращение
              цапфы останавливают и увеличивают давление дляобеспечения сваривания
              поверхностей.
            </p>
            <p>
              8. Сварной шов имеет чешуйчатый вид, что является результатомобдува струей
              сжатого воздуха.
            </p>
            <p>
              <strong>5.</strong> Choose an alternative welding method for the following applications.
              Explain your choice.
            </p>
            <p>
              ü to join some electrical wires to form a circuit
            </p>
            <p>
              ü a transistor can
            </p>
            <p>
              ü parts of a plane which have honeycomb construction
            </p>
            <p>
              ü to join two aluminum sheets laid one onto another
            </p>
            <p>
              <strong>6.</strong> In each line of words (1-4) find the odd one out. Explain your choice.
            </p>
            <p>
              1) low-voltage, gas flame, direct current, discharge
            </p>
            <p>
              2) gas welding, arc welding, termit welding, resistance welding
            </p>
            <p>
              3) friction, torch, flux, filler material
            </p>
            <p>
              4) fusion, filler, heat-affected, unaffected
            </p>

          </div>
        </div>
      </div> <!-- col-md-8 -->
      </div>
      </div>
    </section>

  </main>
  <?php include('../../../fragments/footer.php') ?>
</body>

</html>